name: Test Suite

on:
  push:
    branches:
      - master

jobs:
  check-component-features:
    name: Component Features - Linux
    runs-on: [linux, test-runner]
    steps:
      - uses: actions/checkout@v3
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: cargo install cargo-hack
      - run: make check-component-features
